### ISSUE TITLE
ERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::TaskLoader.__init__()

### ISSUE THREAD

**Issue by mamimaka** [columbia-robovision/decentralized-multiarm#12]
Hi, @huy-ha

Thank you for your open source!

When I try to run `python main.py --mode benchmark --tasks_path benchmark/ --load ours/ours.pth --num_processes 2 --gui`, I get the follow errors. I try to fix them, but fail.

At first, the error is: 
````
(TaskLoader pid=111640) 2023-04-12 22:54:24,948	ERROR worker.py:772 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::TaskLoader.__init__() (pid=111640, ip=192.168.160.188)
(TaskLoader pid=111640)   File "/home/xhr/xhr/mulit_arm/decentralized-multiarm-main/environment/tasks.py", line 342, in __init__
(TaskLoader pid=111640)     assert len(self.files) > 0
(TaskLoader pid=111640) AssertionError
````

In the end, the error is:

````
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    simulate(args, config)
  File "main.py", line 55, in simulate
    observations = ray.get([e.reset.remote() for e in envs])
  File "/home/xhr/anaconda3/envs/multiarm2/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/xhr/anaconda3/envs/multiarm2/lib/python3.7/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::ParallelBenchmarkEnv.reset() (pid=111642, ip=192.168.160.188, repr=<environment.benchmarkEnv.ParallelBenchmarkEnv object at 0x7f48e1a42dd0>)
  File "/home/xhr/xhr/mulit_arm/decentralized-multiarm-main/environment/baseEnv.py", line 582, in reset
    self.setup_task()
  File "/home/xhr/xhr/mulit_arm/decentralized-multiarm-main/environment/baseEnv.py", line 617, in setup_task
    min_task_difficulty=self.min_task_difficulty)
  File "/home/xhr/xhr/mulit_arm/decentralized-multiarm-main/environment/tasks.py", line 282, in setup_next_task
    self.task_loader.get_next_task.remote())
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::TaskLoader.__init__() (pid=111640, ip=192.168.160.188)
  File "/home/xhr/xhr/mulit_arm/decentralized-multiarm-main/environment/tasks.py", line 342, in __init__
    assert len(self.files) > 0
AssertionError
````

My conda environment is created from the provided environment.yml file. My system is ubuntu20.04.

Can you get me some suggestions? I need your help.

**Comment by GuQian-Alex** [comment]
Hello, i also meet the same problem.  It seems there need some .json file for the task.

**Comment by PepsiCo1234** [comment]
Hello friend,I'm glad to have someone to work on this with. I also encountered the same problem, could you tell me in detail how to solve it? I would appreciate it. @huy-ha @mamimaka @GuQian-Alex

**Comment by xrdiao** [comment]
When I changed the `*.json` in line 337 of 'environment/tasks.py' to `*.p`, the error was not reported. This should be caused by the mismatch between the code used by the author and the environment configuration file.
