### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rsample'

### ISSUE THREAD

**Issue by GuancongLuo** [columbia-robovision/decentralized-multiarm#5]
Hi, @huy-ha 

Thank you for your open source!

When I try to run `python main.py --config configs/default.json --tasks_path tasks/ --expert_waypoints expert/ --num_processes 1 --name multiarm_motion_planner`, I get the follow error. I try to fix it, but fail.

```
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    simulate(args, config)
  File "main.py", line 68, in simulate
    for observation in observations]
  File "main.py", line 68, in <listcomp>
    for observation in observations]
  File "C:\1 learning a decentralized multiarm motion planner\decentralized-multiarm\policy\SAC.py", line 165, in act
    reparametrize=self.reparametrize)
  File "C:\anaconda3\envs\multiarm\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\1 learning a decentralized multiarm motion planner\decentralized-multiarm\policy\BaseNet.py", line 187, in forward
    actions = dist.rsample()
AttributeError: 'NoneType' object has no attribute 'rsample'
```

My python version is `pytorch                   1.7.0           py3.7_cuda110_cudnn8_0`.

I have to use pytorch 1.7.0 because cuda 11 no pytorch 1.6.0 .

Can you get me some suggestion?

**Comment by GuancongLuo** [comment]
This problem represent when I use pytorch 1.6.0 . I need your help.

**Comment by huy-ha** [comment]
It looks like you created a conda environment from the provided `environment.yml` file then upgraded Pytorch afterwards? Did the original `environment.yml` file work? 
This happens when the variance matrix to `MultivariateNormal` are invalid, and `generate_dist` returns `None` instead. Did you see any error message before this printing out the mean and variance matrices?

**Comment by GuancongLuo** [comment]
Yes, I use your environment.yml to create codna environment and upgraded Pytorch.

It is original file work, comment ID is  58e746639ac11dd2a1ee61214f5e2966f08f13b2 (HEAD -> main, origin/main, origin/HEAD)

More information.

```
(pid=8568) UnicodeEncodeError: 'ascii' codec can't encode characters in position 191-194: ordinal not in range(128)  
(pid=8568) Exception ignored in: 'ray._raylet.get_py_stack'     
(pid=8568) UnicodeEncodeError: 'ascii' codec can't encode characters in position 191-194: ordinal not in range(128)  
(pid=8568) UnicodeEncodeError: 'ascii' codec can't encode characters in position 191-194: ordinal not in range(128)  
(pid=8568) Exception ignored in: 'ray._raylet.get_py_stack'
(pid=8568) UnicodeEncodeError: 'ascii' codec can't encode characters in position 191-194: ordinal not in range(128)  
(pid=8568) StochasticActor(           
(pid=8568)   (seq_net): LSTM(107, 256, batch_first=True) 
(pid=8568)   (net): Sequential(     
(pid=8568)     (0): Linear(in_features=256, out_features=128, bias=True)  
(pid=8568)     (1): Tanh()   
(pid=8568)     (2): Linear(in_features=128, out_features=64, bias=True) 
(pid=8568)     (3): Tanh() 
(pid=8568)     (4): Linear(in_features=64, out_features=12, bias=True)   
(pid=8568)     (5): Tanh()   
(pid=8568)   )                                                                                                      
(pid=8568) )   
(pid=8568) Q(            
(pid=8568)   (seq_net): LSTM(107, 256, batch_first=True)  
(pid=8568)   (net): Sequential(     
(pid=8568)     (0): Linear(in_features=262, out_features=128, bias=True)
(pid=8568)     (1): Tanh()           
(pid=8568)     (2): Linear(in_features=128, out_features=64, bias=True)
(pid=8568)     (3): Tanh()       
(pid=8568)     (4): Linear(in_features=64, out_features=1, bias=True)
(pid=8568)   )          
(pid=8568) )                                                              
(pid=18840) [TaskLoader] Found 847950 tasks  
UnicodeEncodeError: 'ascii' codec can't encode characters in position 195-198: ordinal not in range(128)
Exception ignored in: 'ray._raylet.get_py_stack' 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 195-198: ordinal not in range(128)   
CUDA error: no kernel image is available for execution on the device
mean:  
tensor([[-0.0502, -0.0679,  0.0589, -0.1602,  0.0603,  0.0016]], 
device='cuda:0', grad_fn=<SplitBackward>)  
variances:                                                                    
tensor([[[2.7922e-05, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],                  
[0.0000e+00, 1.4245e-05, 0.0000e+00, 0.0000e+00, 0.0000e+00,  0.0000e+00],   
[0.0000e+00, 0.0000e+00, 2.7981e-05, 0.0000e+00, 0.0000e+00,  0.0000e+00],    
[0.0000e+00, 0.0000e+00, 0.0000e+00, 1.6754e-05, 0.0000e+00,  0.0000e+00],
[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 4.0590e-05,  0.0000e+00],    
[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.6512e-05]]], 
device='cuda:0', grad_fn=<StackBackward>) 
```

**Comment by huy-ha** [comment]
It looks like you might be using an unsupported version of [PyTorch](https://github.com/pytorch/pytorch/issues/31285)? Do other Pytorch GPU training codebases work for you?

**Comment by GuancongLuo** [comment]
I successfully run evaluation demo, i.e. , `python main.py --mode benchmark --tasks_path benchmark/ --load ours/ours.pth --num_processes 1 --gui
`  and `python benchmark_dynamic.py --mode benchmark --tasks_path benchmark/ --load ours/ours.pth --num_processes 1 --gui`
'

At the same time, I use cnn to train mnist. 
Result: 
```
Epoch:  19 | train loss: 0.0007 | test accuracy: 0.99
Epoch:  19 | train loss: 0.0632 | test accuracy: 0.99
Epoch:  19 | train loss: 0.0000 | test accuracy: 0.99
Epoch:  19 | train loss: 0.0000 | test accuracy: 0.99
Epoch:  19 | train loss: 0.0001 | test accuracy: 0.99
Epoch:  19 | train loss: 0.0000 | test accuracy: 0.99
Epoch:  19 | train loss: 0.0026 | test accuracy: 0.99
tensor([7, 2, 1, 0, 4, 1, 4, 9, 5, 9], device='cuda:0') prediction number
```

So Pytorch GPU training codebases is work.





```
import torch
import torch.nn as nn
import torch.utils.data as Data
import torchvision
 
# torch.manual_seed(1)
 
EPOCH = 20
BATCH_SIZE = 50
LR = 0.001
DOWNLOAD_MNIST = True
 
train_data = torchvision.datasets.MNIST(root='./mnist/', train=True, transform=torchvision.transforms.ToTensor(), download=DOWNLOAD_MNIST,)
train_loader = Data.DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)
 
test_data = torchvision.datasets.MNIST(root='./mnist/', train=False)
 
# !!!!!!!! Change in here !!!!!!!!! #
test_x = torch.unsqueeze(test_data.test_data, dim=1).type(torch.FloatTensor)[:2000].cuda()/255.   # Tensor on GPU
test_y = test_data.test_labels[:2000].cuda()
 
 
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Sequential(nn.Conv2d(in_channels=1, out_channels=16, kernel_size=5, stride=1, padding=2,),
                                   nn.ReLU(), nn.MaxPool2d(kernel_size=2),)
        self.conv2 = nn.Sequential(nn.Conv2d(16, 32, 5, 1, 2), nn.ReLU(), nn.MaxPool2d(2),)
        self.out = nn.Linear(32 * 7 * 7, 10)
 
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)
        output = self.out(x)
        return output
 
cnn = CNN()
 
# !!!!!!!! Change in here !!!!!!!!! #
cnn.cuda()      # Moves all model parameters and buffers to the GPU.
 
optimizer = torch.optim.Adam(cnn.parameters(), lr=LR)
loss_func = nn.CrossEntropyLoss()
 
for epoch in range(EPOCH):
    for step, (x, y) in enumerate(train_loader):
 
        # !!!!!!!! Change in here !!!!!!!!! #
        b_x = x.cuda()    # Tensor on GPU
        b_y = y.cuda()    # Tensor on GPU
 
        output = cnn(b_x)
        loss = loss_func(output, b_y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
 
        if step % 50 == 0:
            test_output = cnn(test_x)
 
            # !!!!!!!! Change in here !!!!!!!!! #
            pred_y = torch.max(test_output, 1)[1].cuda().data  # move the computation in GPU
 
            accuracy = torch.sum(pred_y == test_y).type(torch.FloatTensor) / test_y.size(0)
            print('Epoch: ', epoch, '| train loss: %.4f' % loss, '| test accuracy: %.2f' % accuracy)
 
 
test_output = cnn(test_x[:10])
 
# !!!!!!!! Change in here !!!!!!!!! #
pred_y = torch.max(test_output, 1)[1].cuda().data # move the computation in GPU
 
print(pred_y, 'prediction number')

```

I have no idea to debug for train  multi-arm motion planner. I need your help!

**Comment by huy-ha** [comment]
I've tested the codebase on multiple Ubuntu 18.04 machines with different GPUs and the codebase have worked fine. It looks like you're running on Windows? Could you let me know the details of your setup (OS, GPU, etc.)?

Also, when I asked whether the provided `environment.yml` file works, you said

> It is original file work

So the original environment works? If it did, and you installed some things on top of it, perhaps you could try deleting the conda environment, then recreating it from the yaml file?

Lastly, could you try this minimum example in your multiarm environment and let me know what you see?
```py
import torch

mean = torch.zeros(4)
variances = torch.diag(torch.ones(4))
dist = torch.distributions.MultivariateNormal(mean, variances)
print(dist.rsample())

```

**Comment by GuancongLuo** [comment]
Yes, I running on Windows (OS is Win10 and GPU is RTX3070).

The original environment not work. 

When I try this minimum example in my multiarm environment, I get the following result.

```
(multiarm) C:\1 learning a decentralized multiarm motion planner\pytorch_turturials>python 2_min_rl_test.py
tensor([-0.9783,  0.2628,  1.0374, -0.1527])
```

**Comment by GuancongLuo** [comment]
I ran the training code successfully on ubuntu 20.04 .

Thank you for your help.

Close issue!
