### ISSUE TITLE
How to continue training after being interrupted?

### ISSUE THREAD

**Issue by GuancongLuo** [columbia-robovision/decentralized-multiarm#6]
Hi @huy-ha ,

Thank you for reviewing this issue!

`python main.py --config configs/default.json --tasks_path tasks/ --expert_waypoints expert/ --num_processes 8 --name multiarm_motion_planner_test`

When I was training the network, the training was terminated due to a memory error

```
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    simulate(args, config)
  File "main.py", line 73, in simulate
    remaining_observations=remaining_observations)
  File "main.py", line 41, in step_env
    for obs, env_id in ray.get(step_retval):
  File "/home/robot/anaconda3/envs/multiarm_local/lib/python3.7/site-packages/ray/worker.py", line 1452, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RayOutOfMemoryError): ray::RRTSupervisionEnv.step() (pid=3255, ip=127.0.1.1)
  File "python/ray/_raylet.pyx", line 444, in ray._raylet.execute_task
  File "/home/robot/anaconda3/envs/multiarm_local/lib/python3.7/site-packages/ray/memory_monitor.py", line 140, in raise_if_low_memory
    self.error_threshold))
ray.memory_monitor.RayOutOfMemoryError: More than 95% of the memory on node robot-desktop is used (14.92 / 15.61 GB). The top 10 memory consumers are:

PID	MEM	COMMAND
3252	3.07GiB	ray::SACLearner.get_update()
3149	2.46GiB	python main.py --config configs/default.json --tasks_path tasks/ --expert_waypoints expert/ --num_pr
3259	0.92GiB	ray::RRTSupervisionEnv.step()
3256	0.92GiB	ray::RRTSupervisionEnv
3254	0.92GiB	ray::RRTSupervisionEnv
3253	0.9GiB	ray::RRTSupervisionEnv
3257	0.89GiB	ray::RRTSupervisionEnv
3258	0.7GiB	ray::TaskLoader
3260	0.7GiB	ray::RRTSupervisionEnv.step()
3250	0.7GiB	ray::RRTSupervisionEnv.step()

In addition, up to 0.07 GiB of shared memory is currently being used by the Ray object store. You can set the object store size with the `object_store_memory` parameter when starting Ray.
---
--- Tip: Use the `ray memory` command to list active objects in the cluster.
---

```

I want to start a new training task again based on the results when I stopped training.
For example:
The training mission was aborted for various reasons and the result is `runs/multiarm_motion_planner/ckpt_multiarm_motion_planner_00101`.
So I want to continue training for multiarm_motion_planner base on the result `runs/multiarm_motion_planner/ckpt_multiarm_motion_planner_00101`

I found `'--curriculum_level', type=int,` parameter in the code, but it does not seem to solve the problem.

Can you give me some suggestions?

**Comment by huy-ha** [comment]
You can use `-- load path/to/checkpoint`
